package com.kumofactory.cloud.blueprint.domain.aws;

public enum AwsComponentType {
    VPC, SUBNET, ALB, NLB, EC2, EFS, WAF, ROUTE53, NAT_GATEWAY, RDS_MYSQL, S3, ELASTIC_CACHE, CLOUDFRONT, AUTO_SCALING, PUBLIC_INSTANCE1, PUBLIC_INSTANCE2, PRIVATE_INSTANCE1, PRIVATE_INSTANCE2
}
