name: DEV Build-and-Deploy CI/CD

on:
  push:
    # branches: [ 'dev' ]
    branches: '**'
  
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: kumo-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'


      - name: make application.yml
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash

      - name: make application-dev.yml
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      # Push container image on ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push server-dev image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DATE=$(date "+%y.%m.%d")
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-$DATE ./
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-latest ./

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-$DATE
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-latest

          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:dev-$DATE"

      # - name: Build, tag, and push server-main image to Amazon ECR
      #   if: contains(github.ref, 'main')
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     DATE=$(date "+%y.%m.%d")
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:main-$DATE ./
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:main-latest ./

      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:main-$DATE
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:main-latest

      #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:main-$DATE"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Dev Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST_DEV }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:dev-latest
            docker stop ${{ env.ECR_REPOSITORY }}
            docker run --rm -p 8080:8080 --name kumo-server ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:dev-latest

      # - name: Deploy on Product Server
      #   # if: contains(github.ref, 'main')
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.AWS_HOST_DEV }}
      #     username: ${{ secrets.AWS_SSH_USERNAME }}
      #     key: ${{ secrets.AWS_SSH_KEY }}
      #     script_stop: true
      #     script: |
      #       docker pull $ECR_REGISTRY/$ECR_REPOSITORY:main-latest
      #       docker stop $ECR_REPOSITORY
      #       docker run --rm -p 8080:8080 --name kumo-server $ECR_REGISTRY/$ECR_REPOSITORY:main-latest