name: KUMO-SERVER Build-and-Deploy CI/CD

on:
  push:
    # branches: [ 'main', 'dev' ]
    branches: '**'
  
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: kumo-server-dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'


      - name: make application.yml
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'dev')
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash

      - name: make application-dev.yml
        if: contains(github.ref, 'dev')
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1



      - name: Build, tag, and push image to Amazon ECR
        if: contains(github.ref, 'dev')
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DATE=$(date "+%y.%m.%d")
          docker build -t $ECR_REGISTRY/kumo-server:dev-$DATE ./
          docker build -t $ECR_REGISTRY/kumo-server:dev-latest ./

          docker push $ECR_REGISTRY/kumo-server:dev-$DATE
          docker push $ECR_REGISTRY/kumo-server:dev-latest

          echo "::set-output name=image::$ECR_REGISTRY/kumo-server:dev-$DATE"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST_DEV }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script_stop: true
          script: |
            cd ~
            cat ./test