name: Build Test CI/CD

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#       - name: Build Project
#         run: ./gradlew build
        
      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle build --dry-run
